# If true allow opening local paths in the browser
allow_local_paths = false
skip_authentication = false
fractal_data_domain = "http://localhost"
fractal_backend_url = "http://localhost:8000"
fractal_login_url = "http://localhost:5173/auth/login"
