name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

# cancel in-progress runs that use the same workflow and branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  check-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      # check-manifest is a tool that checks that all files in version control are
      # included in the sdist (unless explicitly excluded)
      - run: pipx run check-manifest

  test:
    name: ${{ matrix.platform }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - run: uv sync --frozen --all-extras
      - run: uv run pytest -v

  deploy-pypi:
    name: Publish to PyPI
    needs: test
    if: success() && startsWith(github.ref, 'refs/tags/') && github.event_name != 'schedule'
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required for trusted publishing on PyPi
      contents: write # Required to write releases

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: "0.12.5"
          enable-cache: false
          python-version: "3.12"
      - run: uv sync --frozen
      - run: uv build
      - uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2


  github-release-create-draft:
    needs: test
    if: success() && startsWith(github.ref, 'refs/tags/') && github.event_name != 'schedule'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - run: gh release create "${GH_REF_NAME}" --draft --title "${GH_REF_NAME}"
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REF_NAME: ${{ github.ref_name }}

  github-release-build-wheel-file:
    needs: github-release-create-draft
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: "0.12.5"
          enable-cache: false
          python-version: "3.12"
      - run: uv sync --frozen
      - run: uv build --verbose
      - run: gh release upload "${GH_REF_NAME}" "dist/$WHEEL_FILENAME"
        env:
          GH_REF_NAME: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}
          WHEEL_FILENAME: "fractal_feature_explorer-${{ github.ref_name }}-py3-none-any.whl"

  github-release-build-pylock-files:
    needs: github-release-create-draft
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        python-version: [skip]
        python-version-underscore: [skip]

        include:
          - python-version: "3.12"
            python-version-underscore: "3_12"
          - python-version: "3.13"
            python-version-underscore: "3_13"
          - python-version: "3.14"
            python-version-underscore: "3_14"
        exclude:
          - python-version: "skip"
            python-version-underscore: "skip"

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: "0.12.5"
          enable-cache: false
          python-version: ${{ matrix.python-version }}
      # Build and upload a pylock file for each Python version
      - run: uv export --frozen --format pylock.toml --no-extra dev --no-emit-project --output-file "$PYLOCK_FILENAME"
        env:
          PYLOCK_FILENAME: "pylock.prod-${{ matrix.python-version-underscore }}.toml"
      - run: gh release upload "${GH_REF_NAME}" "$PYLOCK_FILENAME"
        env:
          GH_REF_NAME: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}
          PYLOCK_FILENAME: "pylock.prod-${{ matrix.python-version-underscore }}.toml"

  github-release-deploy:
    needs: [github-release-build-wheel-file, github-release-build-pylock-files]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - run: gh release edit "${GH_REF_NAME}" --draft=false
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REF_NAME: ${{ github.ref_name }}
