[theme]
primaryColor = "#0099ff"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"
font = "sans serif"

[logger]
level = "debug"
messageFormat = "%(asctime)s - %(levelname)s - [%(name)s:%(lineno)d] - %(message)s"
